"""
Bank & Financial Institution Registry — Bangladesh
====================================================
Comprehensive directory of all 105+ scheduled banks, non-scheduled banks,
financial institutions (NBFIs), and major recruitment portals in Bangladesh.

Categories:
  - central_recruitment: Bankers' Selection Committee Secretariat (BSCS) & Bangladesh Bank
  - state_owned: State-Owned Commercial Banks (SOCBs) (6)
  - specialized: Specialized Development Banks (SDBs) (3)
  - private: Private Commercial Banks - Conventional (33)
  - islami: Private Commercial Banks - Islamic Shariah Based (10)
  - foreign: Foreign Commercial Banks operating in BD (9)
  - digital: Digital Banks (2)
  - non_scheduled: Non-Scheduled Specialized Banks (5)
  - nbfi: Non-Bank Financial Institutions (35)
  - job_portal: Aggregated Job Portals & Media
"""

BANKS = [
    # ================================================================
    # CENTRAL BANK & COMMON PORTALS
    # ================================================================
    {
        "name": "Bangladesh Bank Career",
        "short_name": "BB_MAIN",
        "type": "central_recruitment",
        "career_url": "https://www.bb.org.bd/en/index.php/career",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .content a", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Bangladesh Bank eRecruitment (BSCS Central Recruitment)",
        "short_name": "BB_BSCS",
        "type": "central_recruitment",
        "career_url": "https://erecruitment.bb.org.bd/onlineapp/joblist.php",
        "scrape_config": {"method": "table", "job_container": "table tr", "title_selector": "td:nth-child(2)", "deadline_selector": "td:nth-child(8)"},
        "enabled": True,
    },

    # ================================================================
    # STATE-OWNED COMMERCIAL BANKS (SOCBs) (6)
    # ================================================================
    {
        "name": "Sonali Bank PLC",
        "short_name": "SBL",
        "type": "state_owned",
        "career_url": "https://www.sonalibank.com.bd/career.php",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item, .content-area a", "title_selector": "td:first-child, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Janata Bank PLC",
        "short_name": "JBL",
        "type": "state_owned",
        "career_url": "https://www.jb.com.bd/site/page/career",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item", "title_selector": "td:first-child, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Agrani Bank PLC",
        "short_name": "ABL",
        "type": "state_owned",
        "career_url": "https://www.agranibank.org/index.php/home/career",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-list li, a", "title_selector": "td:first-child, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Rupali Bank PLC",
        "short_name": "RBL",
        "type": "state_owned",
        "career_url": "https://www.rupalibank.com.bd",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item, a", "title_selector": "td:first-child, .title, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "BASIC Bank PLC",
        "short_name": "BASIC",
        "type": "state_owned",
        "career_url": "https://www.basicbanklimited.com/career",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item", "title_selector": "td:first-child, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Bangladesh Development Bank (BDBL)",
        "short_name": "BDBL",
        "type": "state_owned",
        "career_url": "https://www.bdbl.com.bd/career",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item", "title_selector": "td:first-child, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },

    # ================================================================
    # SPECIALIZED DEVELOPMENT BANKS (SDBs) (3)
    # ================================================================
    {
        "name": "Bangladesh Krishi Bank (BKB)",
        "short_name": "BKB",
        "type": "specialized",
        "career_url": "https://www.krishibank.org.bd/career",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item", "title_selector": "td:first-child, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Rajshahi Krishi Unnayan Bank (RAKUB)",
        "short_name": "RAKUB",
        "type": "specialized",
        "career_url": "https://rakub.org.bd/recruitment.php",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item, a", "title_selector": "td:first-child, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Probashi Kollyan Bank",
        "short_name": "PKB",
        "type": "specialized",
        "career_url": "http://www.pkb.gov.bd/site/view/career_circular",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item", "title_selector": "td:first-child, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },

    # ================================================================
    # PRIVATE COMMERCIAL BANKS - CONVENTIONAL (33)
    # ================================================================
    {
        "name": "AB Bank PLC",
        "short_name": "AB_BANK",
        "type": "private",
        "career_url": "https://abbl.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "h3, .title, a", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Bangladesh Commerce Bank",
        "short_name": "BCBL",
        "type": "private",
        "career_url": "https://www.bcblbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Bank Asia PLC",
        "short_name": "BANK_ASIA",
        "type": "private",
        "career_url": "https://www.bankasia-bd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "BRAC Bank PLC",
        "short_name": "BRAC",
        "type": "private",
        "career_url": "https://www.bracbank.com/en/career",
        "scrape_config": {"method": "html", "job_container": ".career-list .career-item, .job-listing .job-item, table tbody tr, .card", "title_selector": "h3, .job-title, a, td:first-child", "link_selector": "a", "deadline_selector": ".deadline, .date, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Bengal Commercial Bank",
        "short_name": "BGCB",
        "type": "private",
        "career_url": "https://www.bgcb.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Citizens Bank PLC",
        "short_name": "CITIZENS",
        "type": "private",
        "career_url": "https://www.citizensbankbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "The City Bank PLC",
        "short_name": "CITY_BANK",
        "type": "private",
        "career_url": "https://www.thecitybank.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, .job-list .item, table tbody tr, .card", "title_selector": "h3, .job-title, a", "link_selector": "a", "deadline_selector": ".deadline, .date"},
        "enabled": True,
    },
    {
        "name": "Community Bank Bangladesh PLC",
        "short_name": "COMMUNITY",
        "type": "private",
        "career_url": "https://www.communitybankbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Dhaka Bank PLC",
        "short_name": "DHAKA_BANK",
        "type": "private",
        "career_url": "https://www.dhakabankltd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Dutch-Bangla Bank (DBBL)",
        "short_name": "DBBL",
        "type": "private",
        "career_url": "https://www.dutchbanglabank.com/career/career-at-dbbl.html",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .content-area a", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Eastern Bank PLC (EBL)",
        "short_name": "EBL",
        "type": "private",
        "career_url": "https://www.ebl.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, .job-opening, table tbody tr, .card", "title_selector": "h3, .title, a", "link_selector": "a", "deadline_selector": ".deadline, .date"},
        "enabled": True,
    },
    {
        "name": "IFIC Bank PLC",
        "short_name": "IFIC",
        "type": "private",
        "career_url": "https://www.ificbank.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Jamuna Bank PLC",
        "short_name": "JAMUNA",
        "type": "private",
        "career_url": "https://www.jamunabankbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Meghna Bank PLC",
        "short_name": "MEGHNA",
        "type": "private",
        "career_url": "https://www.meghnabank.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Mercantile Bank PLC",
        "short_name": "MBL",
        "type": "private",
        "career_url": "https://www.mblbd.com/home/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Midland Bank PLC",
        "short_name": "MIDLAND",
        "type": "private",
        "career_url": "https://www.midlandbankbd.net/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Modhumoti Bank PLC",
        "short_name": "MODHUMOTI",
        "type": "private",
        "career_url": "https://www.modhumotibank.ltd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Mutual Trust Bank (MTB)",
        "short_name": "MTB",
        "type": "private",
        "career_url": "https://www.mutualtrustbank.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, .job-item, table tbody tr, .card", "title_selector": "h3, .title, a", "link_selector": "a", "deadline_selector": ".deadline, .date"},
        "enabled": True,
    },
    {
        "name": "National Bank PLC",
        "short_name": "NBL",
        "type": "private",
        "career_url": "https://www.nblbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "NCC Bank PLC",
        "short_name": "NCCB",
        "type": "private",
        "career_url": "https://www.nccbank.com.bd/career.php",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "NRB Bank PLC",
        "short_name": "NRB_BANK",
        "type": "private",
        "career_url": "https://www.nrbbankbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "NRBC Bank PLC",
        "short_name": "NRBC",
        "type": "private",
        "career_url": "https://www.nrbcommercialbank.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "ONE Bank PLC",
        "short_name": "ONE_BANK",
        "type": "private",
        "career_url": "https://www.onebank.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Padma Bank PLC",
        "short_name": "PADMA",
        "type": "private",
        "career_url": "https://www.padmabankbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Premier Bank PLC",
        "short_name": "PREMIER",
        "type": "private",
        "career_url": "https://www.premierbankltd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Prime Bank PLC",
        "short_name": "PRIME",
        "type": "private",
        "career_url": "https://www.primebank.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, .job-list tr, table tbody tr, .card", "title_selector": "h3, .title, a", "link_selector": "a", "deadline_selector": ".deadline, .date"},
        "enabled": True,
    },
    {
        "name": "Pubali Bank PLC",
        "short_name": "PUBALI",
        "type": "private",
        "career_url": "https://www.pubalibangla.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "SBAC Bank PLC",
        "short_name": "SBAC",
        "type": "private",
        "career_url": "https://www.sbacbank.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Shimanto Bank PLC",
        "short_name": "SHIMANTO",
        "type": "private",
        "career_url": "https://www.shimantobank.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Southeast Bank PLC",
        "short_name": "SOUTHEAST",
        "type": "private",
        "career_url": "https://www.southeastbank.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Trust Bank PLC",
        "short_name": "TRUST",
        "type": "private",
        "career_url": "https://www.tblbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "United Commercial Bank (UCB)",
        "short_name": "UCB",
        "type": "private",
        "career_url": "https://www.ucb.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Uttara Bank PLC",
        "short_name": "UTTARA_BANK",
        "type": "private",
        "career_url": "https://www.uttarabank-bd.com/index.php/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },

    # ================================================================
    # PRIVATE COMMERCIAL BANKS - ISLAMI SHARIAH BASED (10)
    # ================================================================
    {
        "name": "Islami Bank Bangladesh PLC (IBBL)",
        "short_name": "IBBL",
        "type": "islami",
        "career_url": "https://www.islamibankbd.com/career.php",
        "scrape_config": {"method": "html", "job_container": ".career-item, .career-box, table tbody tr, .card", "title_selector": "h3, .title, a", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Al-Arafah Islami Bank",
        "short_name": "AIBL",
        "type": "islami",
        "career_url": "https://www.aibl.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Social Islami Bank (SIBL)",
        "short_name": "SIBL",
        "type": "islami",
        "career_url": "https://www.siblbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "First Security Islami (FSIBL)",
        "short_name": "FSIBL",
        "type": "islami",
        "career_url": "https://www.fsiblbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Shahjalal Islami Bank (SJIBL)",
        "short_name": "SJIBL",
        "type": "islami",
        "career_url": "https://www.sjiblbd.com/career.php",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "EXIM Bank",
        "short_name": "EXIM",
        "type": "islami",
        "career_url": "https://www.eximbankbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Union Bank PLC",
        "short_name": "UNION_BANK",
        "type": "islami",
        "career_url": "https://www.unionbank.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Global Islami Bank",
        "short_name": "GLOBAL_ISLAMI",
        "type": "islami",
        "career_url": "https://www.globalislamibankbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "ICB Islamic Bank",
        "short_name": "ICB_ISLAMIC",
        "type": "islami",
        "career_url": "https://www.icbislamic-bank.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Standard Bank PLC (Islamic)",
        "short_name": "STANDARD_BANK",
        "type": "islami",
        "career_url": "https://www.standardbankbd.com/Career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },

    # ================================================================
    # FOREIGN COMMERCIAL BANKS IN BD (9)
    # ================================================================
    {
        "name": "Standard Chartered Bangladesh",
        "short_name": "SCB",
        "type": "foreign",
        "career_url": "https://www.sc.com/bd/careers/",
        "scrape_config": {"method": "html", "job_container": ".career-item, .job-item, a", "title_selector": "a, .title", "link_selector": "a", "deadline_selector": ".date"},
        "enabled": True,
    },
    {
        "name": "Commercial Bank of Ceylon BD",
        "short_name": "CEYLON",
        "type": "foreign",
        "career_url": "https://www.combank.net/bangladesh/careers",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, a", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "HSBC Bangladesh",
        "short_name": "HSBC",
        "type": "foreign",
        "career_url": "https://www.hsbc.com.bd/1/2/careers",
        "scrape_config": {"method": "html", "job_container": ".career-item, a", "title_selector": "a", "link_selector": "a", "deadline_selector": ".date"},
        "enabled": True,
    },
    {
        "name": "State Bank of India (BD)",
        "short_name": "SBI_BD",
        "type": "foreign",
        "career_url": "https://bd.statebank/careers",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, a", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Habib Bank Limited (HBL BD)",
        "short_name": "HBL_BD",
        "type": "foreign",
        "career_url": "https://www.hbl.com/bangladesh/careers",
        "scrape_config": {"method": "html", "job_container": ".career-item, a", "title_selector": "a", "link_selector": "a", "deadline_selector": ".date"},
        "enabled": True,
    },
    {
        "name": "Woori Bank BD",
        "short_name": "WOORI",
        "type": "foreign",
        "career_url": "https://go.wooribank.com/bd/en/bi/cs/rcrtiInfo.do",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Bank Alfalah (BD)",
        "short_name": "ALFALAH",
        "type": "foreign",
        "career_url": "https://www.bankalfalah.com/bd/careers/",
        "scrape_config": {"method": "html", "job_container": ".career-item, a", "title_selector": "a", "link_selector": "a", "deadline_selector": ".date"},
        "enabled": True,
    },
    {
        "name": "Citibank N.A. (BD)",
        "short_name": "CITI",
        "type": "foreign",
        "career_url": "https://careers.citi.com/",
        "scrape_config": {"method": "html", "job_container": ".career-item, a", "title_selector": "a", "link_selector": "a", "deadline_selector": ".date"},
        "enabled": True,
    },
    {
        "name": "National Bank of Pakistan (BD)",
        "short_name": "NBP_BD",
        "type": "foreign",
        "career_url": "https://www.nbp.com.pk/Careers/",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, a", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },

    # ================================================================
    # DIGITAL BANKS (2)
    # ================================================================
    {
        "name": "Nagad Digital Bank PLC",
        "short_name": "NAGAD_DIGITAL",
        "type": "digital",
        "career_url": "https://nagad.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, .job-item, a", "title_selector": "a, h3", "link_selector": "a", "deadline_selector": ".date"},
        "enabled": True,
    },
    {
        "name": "Kori Digital Bank PLC",
        "short_name": "KORI_DIGITAL",
        "type": "digital",
        "career_url": "https://www.kori.com.bd/",
        "scrape_config": {"method": "html", "job_container": ".career-item, a", "title_selector": "a", "link_selector": "a", "deadline_selector": ".date"},
        "enabled": True,
    },

    # ================================================================
    # NON-SCHEDULED SPECIALIZED BANKS (5)
    # ================================================================
    {
        "name": "Ansar-VDP Unnayan Bank",
        "short_name": "ANSAR_VDP",
        "type": "non_scheduled",
        "career_url": "http://www.ansarvdpbank.gov.bd/site/view/career_circular",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item", "title_selector": "td:first-child, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Karmasangsthan Bank",
        "short_name": "KBANK",
        "type": "non_scheduled",
        "career_url": "http://www.karmasangsthanbank.gov.bd/site/view/career_circular",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item", "title_selector": "td:first-child, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Grameen Bank",
        "short_name": "GRAMEEN",
        "type": "non_scheduled",
        "career_url": "https://grameenbank.org.bd/career",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item, a", "title_selector": "td:first-child, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Jubilee Bank",
        "short_name": "JUBILEE",
        "type": "non_scheduled",
        "career_url": "http://jubileebankbd.com/career",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item", "title_selector": "td:first-child, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Palli Sanchay Bank",
        "short_name": "PALLI_SANCHAY",
        "type": "non_scheduled",
        "career_url": "http://www.pallisanchaybank.gov.bd/site/page/career",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item", "title_selector": "td:first-child, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },

    # ================================================================
    # NON-BANK FINANCIAL INSTITUTIONS (NBFIs) (35)
    # ================================================================
    {
        "name": "Agrani SME Financing",
        "short_name": "AGRANI_SME",
        "type": "nbfi",
        "career_url": "http://www.agranisme.gov.bd/career",
        "scrape_config": {"method": "html", "job_container": "table tbody tr, .career-item", "title_selector": "td:first-child, a", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Alliance Finance PLC",
        "short_name": "ALLIANCE",
        "type": "nbfi",
        "career_url": "https://www.lankanalliance.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Aviva Finance Limited",
        "short_name": "AVIVA",
        "type": "nbfi",
        "career_url": "https://www.avivafinance.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Bangladesh Finance Limited",
        "short_name": "BD_FINANCE",
        "type": "nbfi",
        "career_url": "https://www.bdfinance.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "BIFC",
        "short_name": "BIFC",
        "type": "nbfi",
        "career_url": "https://bifcol.com/career/",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "BIFFL",
        "short_name": "BIFFL",
        "type": "nbfi",
        "career_url": "https://biffl.org.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Bay Leasing & Investment",
        "short_name": "BAY_LEASING",
        "type": "nbfi",
        "career_url": "http://www.blilbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "CVC Finance PLC",
        "short_name": "CVC_FINANCE",
        "type": "nbfi",
        "career_url": "https://www.cvcflbd.com/",
        "scrape_config": {"method": "html", "job_container": ".career-item, a", "title_selector": "a", "link_selector": "a", "deadline_selector": ".date"},
        "enabled": True,
    },
    {
        "name": "DBH Finance PLC",
        "short_name": "DBH",
        "type": "nbfi",
        "career_url": "https://www.dbhfinance.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Fareast Finance & Investment",
        "short_name": "FAREAST_FIN",
        "type": "nbfi",
        "career_url": "https://www.ffilbd.com/",
        "scrape_config": {"method": "html", "job_container": ".career-item, a", "title_selector": "a", "link_selector": "a", "deadline_selector": ".date"},
        "enabled": True,
    },
    {
        "name": "FAS Finance & Investment",
        "short_name": "FAS_FINANCE",
        "type": "nbfi",
        "career_url": "https://www.fasbd.com/",
        "scrape_config": {"method": "html", "job_container": ".career-item, a", "title_selector": "a", "link_selector": "a", "deadline_selector": ".date"},
        "enabled": True,
    },
    {
        "name": "First Finance Limited",
        "short_name": "FIRST_FIN",
        "type": "nbfi",
        "career_url": "https://www.first-finance.com.bd/",
        "scrape_config": {"method": "html", "job_container": ".career-item, a", "title_selector": "a", "link_selector": "a", "deadline_selector": ".date"},
        "enabled": True,
    },
    {
        "name": "GSP Finance",
        "short_name": "GSP_FINANCE",
        "type": "nbfi",
        "career_url": "http://www.gspfinance.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Hajj Finance",
        "short_name": "HAJJ_FINANCE",
        "type": "nbfi",
        "career_url": "http://www.hajjfinance.net/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "IDLC Finance PLC",
        "short_name": "IDLC",
        "type": "nbfi",
        "career_url": "https://idlc.com/career.php",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "IIDFC PLC",
        "short_name": "IIDFC",
        "type": "nbfi",
        "career_url": "http://www.iidfc.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "IDCOL",
        "short_name": "IDCOL",
        "type": "nbfi",
        "career_url": "https://idcol.org/home/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, .title, td:first-child", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "International Leasing (ILFSL)",
        "short_name": "ILFSL",
        "type": "nbfi",
        "career_url": "http://www.ilfsl.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "IPDC Finance Ltd",
        "short_name": "IPDC",
        "type": "nbfi",
        "career_url": "https://www.ipdcbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .job-card", "title_selector": "a, .title, h3, td:first-child", "link_selector": "a", "deadline_selector": ".deadline, .date, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Islamic Finance (IFIL)",
        "short_name": "IFIL",
        "type": "nbfi",
        "career_url": "http://www.ifilbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "LankaBangla Finance PLC",
        "short_name": "LANKABANGLA",
        "type": "nbfi",
        "career_url": "https://www.lankabangla.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr, .card", "title_selector": "a, .title, h3", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Meridian Finance",
        "short_name": "MERIDIAN",
        "type": "nbfi",
        "career_url": "http://www.meridianfinancebd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "MIDAS Financing PLC",
        "short_name": "MIDAS",
        "type": "nbfi",
        "career_url": "http://www.mfl.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "National Finance PLC",
        "short_name": "NATIONAL_FIN",
        "type": "nbfi",
        "career_url": "http://www.nfl.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "National Housing Finance",
        "short_name": "NATIONAL_HOUSING",
        "type": "nbfi",
        "career_url": "http://www.nationalhousingbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "People's Leasing",
        "short_name": "PEOPLES_LEASING",
        "type": "nbfi",
        "career_url": "http://www.plfsbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Phoenix Finance",
        "short_name": "PHOENIX",
        "type": "nbfi",
        "career_url": "http://phoenixfinance.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Premier Leasing & Finance",
        "short_name": "PREMIER_LEASING",
        "type": "nbfi",
        "career_url": "http://www.premierleasing.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "Prime Finance & Investment",
        "short_name": "PRIME_FIN",
        "type": "nbfi",
        "career_url": "http://www.primefinancebd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "SABINCO",
        "short_name": "SABINCO",
        "type": "nbfi",
        "career_url": "http://www.sabinco.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "SFIL Finance PLC",
        "short_name": "SFIL",
        "type": "nbfi",
        "career_url": "http://www.sfilbd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "UAE-Bangladesh (UBICO)",
        "short_name": "UBICO",
        "type": "nbfi",
        "career_url": "https://ubinco.com/",
        "scrape_config": {"method": "html", "job_container": ".career-item, a", "title_selector": "a", "link_selector": "a", "deadline_selector": ".date"},
        "enabled": True,
    },
    {
        "name": "Union Capital Limited",
        "short_name": "UNION_CAPITAL",
        "type": "nbfi",
        "career_url": "http://www.unicap-bd.com/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, td:first-child", "link_selector": "a", "deadline_selector": "td:last-child"},
        "enabled": True,
    },
    {
        "name": "United Finance Limited",
        "short_name": "UFL",
        "type": "nbfi",
        "career_url": "http://www.ulc.com.bd/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, .title, td:first-child", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
    {
        "name": "Uttara Finance",
        "short_name": "UTTARA_FIN",
        "type": "nbfi",
        "career_url": "http://www.uttarafinance.biz/career",
        "scrape_config": {"method": "html", "job_container": ".career-item, table tbody tr", "title_selector": "a, .title, td:first-child", "link_selector": "a", "deadline_selector": ".deadline, td:last-child"},
        "enabled": True,
    },
]

# ================================================================
# JOB PORTALS & AGGREGATORS
# ================================================================
JOB_PORTALS = [
    {
        "name": "Bangladesh Bank e-Recruitment",
        "short_name": "BB_BSCS",
        "type": "central_recruitment",
        "career_url": "https://erecruitment.bb.org.bd/onlineapp/joblist.php",
        "enabled": True,
    },
    {
        "name": "bdjobs.com (Banking & Finance Category)",
        "short_name": "BDJOBS",
        "type": "job_portal",
        "career_url": "https://api.bdjobs.com/Jobs/api/JobSearch/GetJobSearch",
        "enabled": True,
    },
    {
        "name": "Skill Jobs (Bank & Financial Institution)",
        "short_name": "SKILL_JOBS",
        "type": "job_portal",
        "career_url": "https://skill.jobs/browse-jobs?search=bank",
        "enabled": True,
    },
    {
        "name": "LinkedIn BD Bank Jobs",
        "short_name": "LINKEDIN_BD",
        "type": "job_portal",
        "career_url": "https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords=bank&location=Bangladesh&geoId=106215326",
        "enabled": True,
    },
    {
        "name": "BDJobsToday (Bank/Finance/Insurance)",
        "short_name": "BDJOBSTODAY",
        "type": "image_aggregator",
        "career_url": "https://bdjobstoday.com/jobs.php?cat=3&cat_name=Bank/Finance/Insurance",
        "enabled": True,
    },
    {
        "name": "Chakrir Khobor (Bank Jobs Media)",
        "short_name": "CHAKRIR_KHOBOR",
        "type": "image_aggregator",
        "career_url": "https://chakrirkhobor.com.bd/tag/bank-jobs/",
        "enabled": True,
    },
]

ALL_SOURCES = BANKS + JOB_PORTALS


def get_enabled_sources():
    """Return all sources that are actively monitored."""
    return [s for s in BANKS if s.get("enabled", True)]


def get_enabled_portals():
    """Return all active job portals and aggregators."""
    return [p for p in JOB_PORTALS if p.get("enabled", True)]


def get_sources_by_type(source_type: str):
    """Filter sources by sector type."""
    return [s for s in ALL_SOURCES if s.get("type") == source_type and s.get("enabled", True)]

